---
apiVersion: v1
kind: Pod
metadata:
  name: host-port
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "Host_Ports"    
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000       
  containers: 
  - name: host-port
    image: kubernetes/pause
    ports:
    - containerPort: 80
      hostPort: 80