---
apiVersion: v1
kind: Pod
metadata:
  name: selinux-pod
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "SELinux"        
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000       
    seLinuxOptions:
      user: foo
  containers: 
  - name: selinux
    image: kubernetes/pause
---
apiVersion: v1
kind: Pod
metadata:
  name: selinux-ctnr
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "SELinux"          
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000       
  containers: 
  - name: selinux
    image: kubernetes/pause
    securityContext:
      seLinuxOptions:
        level: "s0:c123,c456"
---
apiVersion: v1
kind: Pod
metadata:
  name: selinux-init-ctnr
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "SELinux"          
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000       
  initContainers:
    - name: init
      image: busybox
      command: ["sleep", "1"]
      securityContext:
        seLinuxOptions:
          level: "s0:c123,c456"
  containers: 
  - name: selinux
    image: kubernetes/pause