---
apiVersion: v1
kind: Pod
metadata:
  name: host-namespaces-network
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "Host_Namespaces"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000    
  hostNetwork: true
  containers:
  - name: host-namespaces-network
    image: gcr.io/google-containers/pause
---
apiVersion: v1
kind: Pod
metadata:
  name: host-namespaces-pid
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "Host_Namespaces"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000       
  hostPID: true
  containers: 
  - name: host-namespaces-pid
    image: gcr.io/google-containers/pause
---
apiVersion: v1
kind: Pod
metadata:
  name: host-namespaces-ipc
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "Host_Namespaces"
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000       
  hostIPC: true
  containers: 
  - name: host-namespaces-ipc
    image: gcr.io/google-containers/pause