---
apiVersion: v1
kind: Pod
metadata:
  name: sysctls
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "Sysctls"  
spec:
  securityContext:
    sysctls:
      - name: kernel.random.poolsize
        value: "2048"
  containers: 
  - name: sysctls
    image: kubernetes/pause