---
apiVersion: v1
kind: Pod
metadata:
  name: apparmor
  labels:
    pod-security-standards/policy: "Baseline"
    pod-security-standards/control: "AppArmor"
  annotations:
    container.apparmor.security.beta.kubernetes.io/apparmor: localhost/customprofile
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000         
  containers: 
  - name: apparmor
    image: kubernetes/pause