apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../baseline

resources:
- test-restrict-volume-types.yaml
- test-deny-privilege-escalation.yaml
- test-require-run-as-nonroot.yaml
- test-non-root-groups.yaml
- test-restrict-seccomp.yaml