---
apiVersion: v1
kind: Pod
metadata:
  name: nonroot-pod
  labels:
    pod-security-standards/policy: "Restricted"
    pod-security-standards/control: "Running_as_Non-root"    
spec:
  securityContext:
    runAsNonRoot: false
  containers: 
  - name: busybox
    image: busybox
    command: ["sleep", "9999"]
---
apiVersion: v1
kind: Pod
metadata:
  name: root-pod
  labels:
    pod-security-standards/policy: "Restricted"
    pod-security-standards/control: "Running_as_Non-root"     
spec:
  securityContext:
    runAsNonRoot: true
  containers: 
  - name: root-pod
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      runAsNonRoot: false
---
apiVersion: v1
kind: Pod
metadata:
  name: root-init-ctnr
  labels:
    pod-security-standards/policy: "Restricted"
    pod-security-standards/control: "Running_as_Non-root"  
spec:
  securityContext:
    runAsNonRoot: true
  initContainers:
  - name: root-init-ctnr
    image: busybox
    command: ["sleep", "1"]
    securityContext:
      runAsNonRoot: false
  containers: 
  - name: pause
    image: kubernetes/pause