---
apiVersion: v1
kind: Pod
metadata:
  name: privileged
  labels:
    pod-security-standards/policy: "Restricted"
    pod-security-standards/control: "Privilege_Escalation"  
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000       
  containers: 
  - name: privileged
    image: busybox
    command: ["sleep", "9999"]
    securityContext:
      allowPrivilegeEscalation: true